default: &default
  adapter: postgresql
  encoding: unicode
  host: host.docker.internal
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mingle_mate_api_development

test:
  <<: *default
  database: mingle_mate_api_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

