default: &default
  adapter: postgresql
  encoding: unicode
  username: sattar
  password: sattar
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mingle_mate_api_development

test:
  <<: *default
  database: mingle_mate_api_test

production:
  <<: *default
  database: mingle_hvmn
  username: sattar
  password: <%= ENV["DATABASE_URL"] %>
